# Generated by Django 4.2.13 on 2024-07-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message", name="seen", field=models.BooleanField(default=False),
        ),
    ]
