# Generated by Django 4.2.13 on 2024-07-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_message_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/images/profilepic"
            ),
        ),
    ]
