# Generated by Django 4.2.13 on 2024-07-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        ),
    ]
