# Generated by Django 4.2.13 on 2024-08-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_transaction_additional_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.CharField(blank=True, null=True),
        ),
    ]
