# Generated by Django 4.2.13 on 2024-08-10 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_hiring_customer_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="job_posting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="user.jobposting",
            ),
        ),
    ]
